############# English navigation ##############

# main menu


[[main]]
name = "Home"
url = "#"
weight = 1

[[main]]
name = "Resume"
url = "https://arisylafeta.github.io/resume/"
weight = 2

[[main]]
name = "Contact"
url = "https://arisylafeta.github.io/resume/#contact"
weight = 3