############# English navigation ##############

# main menu


[[main]]
name = "Data Science & AI"
url = "categories/datascience"
weight = 1

[[main]]
name = "Finance"
url = "categories/finance"
weight = 2

[[main]]
name = "Block Chain & DAPP"
url = "categories/blockchain"
weight = 3